import jsPDF from "jspdf"

export function generatePDFReport(data) {
  const doc = new jsPDF()

  let y = 10

  doc.setFont("Helvetica")
  doc.setFontSize(14)

  doc.text("Solar System Report", 10, y)
  y += 10

  doc.setFontSize(10)

  const addLine = (label, value) => {
    doc.text(`${label}: ${value ?? "-"}`, 10, y)
    y += 7
  }

  addLine("Project Name", data.name)
  addLine("Location", data.location)
  addLine("Daily Consumption (kWh)", data.dailyConsumption)
  addLine("Peak Sun Hours", data.sunHours)
  addLine("System Power (kW)", data.systemPower)
  addLine("Panel Count", data.panelCount)
  addLine("Battery Capacity (kWh)", data.batteryCapacity)
  addLine("Inverter Power (kW)", data.inverterPower)

  y += 10

  doc.text("Generated by Solar App", 10, y)

  doc.save("solar-report.pdf")
}
